### ISSUE TITLE
Q: binutils version to use?

### ISSUE THREAD

**Issue by mlafeldt** [ZirconiumX/prussia#3]
What version/flavor of binutils is required use prussia? And how did you install/compile it?

The ps2toolchain project uses binutils 2.14 with this patch: https://github.com/ps2dev/ps2toolchain/blob/master/patches/binutils-2.14-PS2.patch

**Comment by ZirconiumX** [comment]
It's designed to be purely LLVM - binutils is never used here. The reason
the SDK is a rewrite and not bindings to PS2SDK is that it uses a custom
R5900-specific ELF mode, which makes it impossible to link code with any
other language.

However, I know @frno7 has been working on binutils for R5900, and I think
a very modern (>= 2.29) upstream binutils might work.

**Comment by mlafeldt** [comment]
But you state in the README that one should install binutils for MIPS, no?

I get this error when trying to build the project:

```
$ cargo xbuild --target ps2.json
...
error: linker `mips64el-none-elf-ld` not found
  |
  = note: No such file or directory (os error 2)
```

**Comment by mlafeldt** [comment]
I guess I need to install binutils like this https://github.com/bokuweb/docker-rust-gba/blob/ff0de7b1b8b5502f983b10c71082b5d5dfcac364/Dockerfile#L10 with `--target=mips64el-none-elf` but I'm not sure.

**Comment by ZirconiumX** [comment]
Then yes, you'll need binutils made with ,`./configure
--target=mips64el-none-elf`. It's been a while since I worked on this,
sorry.

**Comment by mlafeldt** [comment]
Thanks!

This Dockerfile does the job for me under OS X:

```
FROM rustlang/rust:nightly

RUN wget http://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.gz && \
  tar -zxvf binutils-2.27.tar.gz && \
  cd binutils-2.27 && \
  ./configure --target=mips64el-none-elf && \
  make && \
  make install

RUN cargo install cargo-xbuild
RUN rustup component add rust-src

WORKDIR /src
CMD ["/bin/bash"]
```

The code requires some changes to compile with a recent Rust version. I'm going to open a PR later.

**Comment by mlafeldt** [comment]
One more thing: maybe the project could be compiled using https://github.com/rust-embedded/cross but I haven't tried yet.

**Comment by ZirconiumX** [comment]
GCC version is not particularly relevant in the context of a Rust program.

**Comment by mlafeldt** [comment]
> The code requires some changes to compile with a recent Rust version. I'm going to open a PR later.

Here we go: https://github.com/ZirconiumX/prussia/pull/4
